version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8080
    depends_on:
      - db